2025-06-07 11:23:18 - MatchmakingViewModel - ERROR - Error in add_to_waiting_list for user 777: 'dict' object has no attribute 'class1'
2025-06-07 11:27:52 - root - ERROR - ❌ Failed to sync commands: 400 Bad Request (error code: 50035): Invalid Form Body
In 8: Application command names must be unique
2025-06-07 11:28:33 - MatchmakingViewModel - ERROR - ❌ Error in background_match_check: 'dict' object has no attribute 'user_name'
2025-06-07 11:28:33 - MatchmakingViewModel - ERROR - Traceback (most recent call last):
  File "C:\Users\owner\svRatings\viewmodels\matchmaking_vm.py", line 251, in background_match_check
    user_name = user_data.user_name if user_data else user.display_name
                ^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'user_name'

2025-06-07 11:28:58 - ResultView - ERROR - Error in check_results: 'dict' object has no attribute 'id'
2025-06-07 11:39:10 - root - ERROR - ❌ Failed to sync commands: 400 Bad Request (error code: 50035): Invalid Form Body
In 8: Application command names must be unique
